#define APP_NAME                "RFM69GW"
#define APP_VERSION             "1.0.1"
#define APP_AUTHOR              "xose.perez@gmail.com"
#define APP_WEBSITE             "http://tinkerman.cat"
#define MANUFACTURER			"TINKERMAN"
